baseURL = 'https://todayis-sunny.github.io/'
languageCode = 'ko-kr'
title = 'todayis-sunny blog'
theme = 'Book'

[params]
  BookLogo = 'profile.png'
  BookFavicon = 'profile.png'
  [params.BookMenu]
    profileImage = 'profile.png'
    githubLink = 'https://github.com/todayis-sunny'